"""Agent Runtime Protocol v1 event and coordination core."""

from .commands import CommandQueue
from .errors import (
    CommandConflict,
    EntityNotFound,
    ExecutionError,
    IdempotencyConflict,
    InvalidTransition,
    LeaseConflict,
    MissingExpectedRevision,
    RelationConstraintError,
    RevisionConflict,
    ValidationError,
)
from .events import (
    EVENT_SCHEMA,
    AppendResult,
    EventEnvelope,
    EventScope,
    Evidence,
    ExecutionSnapshot,
    ProducerRef,
    StoredEvent,
    new_id,
)
from .models import (
    AgentLifecycle,
    AppendStatus,
    AssignmentLifecycle,
    Command,
    CommandStatus,
    Entity,
    EntityKind,
    EntityRelation,
    Lease,
    LeaseStatus,
    ProducerMode,
    ProducerAcknowledgement,
    Projection,
    RelationKind,
    ResyncRequired,
    RunActivity,
    RunLifecycle,
    SpanLifecycle,
    TaskLifecycle,
    TerminalLifecycle,
    WaitReason,
)
from .projector import aggregate_for_event, project_event, stream_for_event
from .store import ExecutionStore, ExecutionSubscription

__all__ = [
    "EVENT_SCHEMA",
    "AgentLifecycle",
    "AppendResult",
    "AppendStatus",
    "AssignmentLifecycle",
    "Command",
    "CommandConflict",
    "CommandQueue",
    "CommandStatus",
    "Entity",
    "EntityKind",
    "EntityNotFound",
    "EntityRelation",
    "EventEnvelope",
    "EventScope",
    "Evidence",
    "ExecutionError",
    "ExecutionSnapshot",
    "ExecutionStore",
    "ExecutionSubscription",
    "IdempotencyConflict",
    "InvalidTransition",
    "Lease",
    "LeaseConflict",
    "LeaseStatus",
    "MissingExpectedRevision",
    "ProducerMode",
    "ProducerAcknowledgement",
    "ProducerRef",
    "Projection",
    "RelationConstraintError",
    "RelationKind",
    "ResyncRequired",
    "RevisionConflict",
    "RunActivity",
    "RunLifecycle",
    "SpanLifecycle",
    "StoredEvent",
    "TaskLifecycle",
    "TerminalLifecycle",
    "ValidationError",
    "WaitReason",
    "aggregate_for_event",
    "new_id",
    "project_event",
    "stream_for_event",
]
